# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2ebh1DfZkDOb2kCis_tmFGaK0RvmKDb
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np
import pandas as pd

# Crear la aplicación Flask
app = Flask(__name__)

# Cargar el modelo entrenado
model_path = "modelo_voting_classifier.pkl"
pipeline = joblib.load(model_path)

# Endpoint para predecir
@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Obtener datos del cliente en formato JSON
        data = request.json

        # Convertir datos a DataFrame
        input_data = pd.DataFrame([data])

        # Realizar la predicción
        prediction = pipeline.predict(input_data)[0]

        # Devolver la predicción
        return jsonify({"prediction": prediction})

    except Exception as e:
        return jsonify({"error": str(e)}), 400

# Iniciar el servidor
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)